### ISSUE TITLE
Is this not the same as pass?

### ISSUE THREAD

**Issue by CarliJoy** [drduh/Purse#1]
Is this software not the same as pass?
https://www.2daygeek.com/pass-command-line-password-manager-linux/

Why rewrite it?
Or what is the difference?

**Comment by drduh** [comment]
The functionality is very similar, but there are differences in the implementation that you can see by inspecting the source code. Essentially, they're both simple wrappers around GPG. I didn't "rewrite" pass, I actually created pwd.sh without having heard of pass, and later modified it to make this with a more robust encryption scheme to make Purse. Hope that helps.
