### ISSUE TITLE
tr: Illegal byte sequence

### ISSUE THREAD

**Issue by rwitlmarkf** [drduh/Purse#4]
I tried to use purse.sh and found that it was giving an error "tr: Illegal byte sequence"

Inspecting the code I see it was happening when using /dev/urandom to select a filename for the stored data in the purse. Google helped me find https://unix.stackexchange.com/questions/45404/why-cant-tr-read-from-dev-urandom-on-osx which helped me understand I needed an LC_ALL=C added to the script to override my default LANG. 

Thanks for your tutorials/notes - I found them very helpful.

**Comment by drduh** [comment]
Can you try it now that https://github.com/drduh/Purse/pull/3 is merged? Thanks!

**Comment by sparks3875392** [comment]
Yes. That works. Thanks.
